name: Backend

on:
  push:
    branches: [ dev, production, main ]
  pull_request:
    branches: [ dev, production, main ]
   
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
    
    - name: Run tests
      working-directory: ./
      run: |
        go test -v ./...